backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: 'equipment'
    label: 'Equipment'
    folder: '/src/equipment/{title}'
    create: true
    slug: 'index'
    editor:
      preview: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string', required: false }
      - { label: 'Category', name: 'category', widget: 'string', required: false }
      - { label: 'Image', name: 'image', widget: 'string', required: false }
      - { label: 'Source', name: 'source', widget: 'string', required: false }
      - { label: 'Data', name: 'data', widget: 'text', required: false }