backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: 'equipment'
    label: 'Equipment'
    folder: 'content/equipment/'
    create: true
    slug: 'index'
    media_folder: ''
    public_folder: ''
    path: '{{title}}/index'
    editor:
      preview: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Category', name: 'category', widget: 'string' }
      - { label: 'Image', name: 'image', widget: 'string' }
      - { label: 'Source', name: 'source', widget: 'string' }
      - { label: 'Data', name: 'data', widget: 'markdown' }